Repository JBA-jeju-basketball-association/JBA-FE, pull requests merged in 2024-07, with the labels that each got.

#104 [Feature] admin페이지 (갤러리,게시물(검색x))
  src/app/App.tsx
  src/entities/admin/index.ts
  src/entities/admin/ui/adminBasicForm.module.css
  src/entities/admin/ui/adminBasicForm.tsx
  src/features/admin/index.ts
  src/features/admin/ui/AdminCompetitionListData.module.css
  src/features/admin/ui/AdminCompetitionListData.tsx
  src/features/admin/ui/AdminGalleryListData.module.css
  src/features/admin/ui/AdminGalleryListData.tsx
  src/features/admin/ui/AdminPostListData.module.css
  src/features/admin/ui/AdminPostListData.tsx
  src/features/admin/ui/AdminSearchForm.module.css
  src/features/admin/ui/adminSearchForm.tsx
  src/features/gallery/ui/GalleryDetailModal.tsx
  src/features/gallery/ui/GalleryEdit.tsx
  src/pages/admin/adminUtils/adminCompetitionTitle.ts
  src/pages/admin/adminUtils/adminGalleryTitle.ts
  src/pages/admin/adminUtils/adminPostTitle.ts
  src/pages/admin/adminUtils/adminUserTitle.ts
  src/pages/admin/api/useAdminCompotitionDatas.ts
  src/pages/admin/api/useAdminGalleryDatas.ts
  src/pages/admin/api/useAdminPostDatas.ts
  src/pages/admin/ui/Admin.tsx
  src/pages/admin/ui/AdminCompetition.module.css
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.module.css
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.module.css
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.module.css
  src/pages/admin/ui/AdminUser.tsx
  src/pages/galleryPages/api/useGalleryDelete.ts
  src/pages/galleryPages/api/useGalleryDetailData.ts
  src/pages/galleryPages/api/useGalleryEdit.ts
  src/pages/galleryPages/api/useGalleryUpload.ts
  src/pages/galleryPages/ui/GalleryEditPage.tsx
  src/shared/hook/useFileDownload.ts
  src/shared/type/AdminType.ts
  src/shared/ui/CategoryList/CategoryList.module.css
  src/shared/ui/CategoryList/CategoryList.tsx
  src/shared/ui/galleryCard/GalleryCard.tsx
  src/shared/ui/index.ts
  src/utils/icon/index.tsx
Labels: 개발

#111 Fix login
  package.json
  src/app/App.tsx
  src/entities/MenuBar/ui/MenuBar.tsx
  src/features/signup/api/checkEmailCodeApi.ts
  src/features/signup/api/sendEmailApi.ts
  src/features/signup/api/signUpApi.ts
  src/features/signup/api/type.ts
  src/features/signup/lib/checkloginInPutData.ts
  src/features/signup/ui/BirthdayInput/Birthday.module.css
  src/features/signup/ui/BirthdayInput/Birthday.tsx
  src/features/signup/ui/BirthdayInput/DayOfBirthday.tsx
  src/features/signup/ui/CheckEmail/CheckEmail.module.css
  src/features/signup/ui/CheckEmail/CheckEmail.tsx
  src/features/signup/ui/GenderInput/Gender.module.css
  src/features/signup/ui/GenderInput/Gender.tsx
  src/features/signup/ui/SignUpInput.module.css
  src/features/signup/ui/SignUpInput.tsx
  src/features/signup/ui/SignupForm.tsx
  src/features/signup/ui/SignupFrom.module.css
  src/pages/loginPage/ui/LoginPage.module.css
  src/pages/loginPage/ui/LoginPage.tsx
  src/pages/signUp/index.ts
  src/pages/signUp/ui/SignUpPage/SignUpPage.module.css
  src/pages/signUp/ui/SignUpPage/SignUpPage.tsx
  src/shared/api/Api.ts
  src/shared/api/NormalApi.ts
  src/shared/api/UseAxiosInterceptor.ts
  src/shared/base.css
  src/widgets/signUp/api/FetchCheckCertificationNum.ts
  src/widgets/signUp/api/FetchSendCertificationEmail.ts
  src/widgets/signUp/api/FetchSignUp.ts
  src/widgets/signUp/index.ts
  src/widgets/signUp/model/BirthHandler.ts
  src/widgets/signUp/model/PhoneNumHandler.ts
  src/widgets/signUp/ui/SignUpForm.module.css
  src/widgets/signUp/ui/SignUpForm.tsx
  yarn.lock
Labels: 개발

#110 [Feat] 게시글 수정 페이지 - 첨부파일 수정 기능 구현 & css 수정
  package-lock.json
  src/app/App.tsx
  src/entities/postListTable/ui/NoticeCard.module.css
  src/entities/postListTable/ui/NoticeCard.tsx
  src/entities/postListTable/ui/PostListRow.module.css
  src/entities/postListTable/ui/PostListRow.tsx
  src/entities/postListTable/ui/PostListTable.module.css
  src/pages/competitionPage/ui/CompetitionPage.tsx
  src/pages/galleryPages/api/useGalleryDatas.ts
  src/pages/postPage/api/AddPostRequest.ts
  src/pages/postPage/api/DeletePost.ts
  src/pages/postPage/api/EditPostRequest.ts
  src/pages/postPage/api/GetFilesUrlRequest.ts
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.module.css
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.module.css
  src/pages/postPage/ui/PostListPage.tsx
  src/pages/postPage/ui/UpdatePostPage.module.css
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/type/PostType.ts
  src/shared/ui/regitUpdateDeleteButton/RegitUpdateDeleteButton.module.css
  src/utils/query/queryProvider.tsx
Labels: 버그, 개발

#116 [Feature] 관리자페이지 (갤러리, 게시물) 검색 폼 구현 2차
  src/entities/admin/ui/adminBasicForm.module.css
  src/entities/admin/ui/adminBasicForm.tsx
  src/entities/gallery/ui/GalleryImageInput.tsx
  src/features/admin/index.ts
  src/features/admin/ui/AdminGalleryListData.tsx
  src/features/admin/ui/AdminPostListData.module.css
  src/features/admin/ui/AdminPostListData.tsx
  src/features/admin/ui/AdminSearchForm.module.css
  src/features/admin/ui/AdminSearchForm.tsx
  src/features/admin/ui/adminSearchForm.tsx
  src/features/gallery/ui/GalleryEdit.tsx
  src/pages/admin/adminUtils/adminGalleryTitle.ts
  src/pages/admin/adminUtils/adminPostTitle.ts
  src/pages/admin/api/useAdminGalleryDatas.ts
  src/pages/admin/api/useAdminPostDatas.ts
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.tsx
  src/shared/hook/useFormattedDate.ts
  src/shared/model/stores/AdminGalleryStore.ts
  src/shared/model/stores/AdminPostStore.ts
  src/shared/type/AdminType.ts
  src/shared/ui/CategoryList/CategoryList.tsx
  src/shared/ui/galleryForm/GalleryForm.tsx
Labels: 개발

#117 [FEAT] chairmanPage 구현
  public/chairman/chairman.png
  src/app/App.tsx
  src/entities/MenuBar/lib/menrLink.ts
  src/entities/chairmanGreeting/index.ts
  src/entities/chairmanGreeting/ui/ChairmanGreeting.module.css
  src/entities/chairmanGreeting/ui/ChairmanGreeting.tsx
  src/pages/chairmanPage/index.ts
  src/pages/chairmanPage/ui/ChairmanPage.module.css
  src/pages/chairmanPage/ui/ChairmanPage.tsx
Labels: 개발

#118 [Feat] faq page ui 작업
  public/faqImg/arrowDown.png
  src/app/App.tsx
  src/entities/MenuBar/lib/menrLink.ts
  src/entities/faqListTable/index.ts
  src/entities/faqListTable/ui/FAQListRow.module.css
  src/entities/faqListTable/ui/FAQListRow.tsx
  src/entities/faqListTable/ui/FAQListTable.module.css
  src/entities/faqListTable/ui/FAQListTable.tsx
  src/pages/faqPage/index.ts
  src/pages/faqPage/model/mockData.ts
  src/pages/faqPage/type/index.ts
  src/pages/faqPage/ui/FaqPage.module.css
  src/pages/faqPage/ui/FaqPage.tsx
Labels: 개발

#119 회원가입 이메일 발송 api 요청 변경
  src/widgets/signUp/api/FetchSendCertificationEmail.ts
Labels: 개발

#121 fix: 로그인 및 리프레시 토큰 로직 cookie 사용으로 변경
  .gitignore
  package.json
  src/features/header/api/FetchLogout.ts
  src/features/header/ui/LoginButton.tsx
  src/pages/loginPage/api/FetchLogin.ts
  src/pages/loginPage/ui/LoginPage.tsx
  src/shared/api/Api.ts
  src/shared/api/NormalApi.ts
  src/shared/api/UseAxiosInterceptor.ts
  src/shared/model/stores/UserStore.ts
Labels: 개발

#127 [FIX] 갤러리페이지, 업로드, 수정에 로딩스피너 추가, 엑셀 구현
  package-lock.json
  package.json
  src/features/admin/ui/AdminCompetitionListData.tsx
  src/features/admin/ui/AdminGalleryListData.module.css
  src/features/admin/ui/AdminGalleryListData.tsx
  src/features/gallery/ui/GalleryEdit.tsx
  src/features/gallery/ui/GalleryUpload.tsx
  src/pages/admin/adminUtils/adminCompetitionTitle.ts
  src/pages/admin/adminUtils/adminGalleryTitle.ts
  src/pages/admin/adminUtils/adminPostTitle.ts
  src/pages/admin/adminUtils/adminUserTitle.ts
  src/pages/admin/ui/AdminCompetition.module.css
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.module.css
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.module.css
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.module.css
  src/pages/admin/ui/AdminUser.tsx
  src/pages/galleryPages/ui/GalleryEditPage.tsx
  src/pages/galleryPages/ui/GalleryPage.module.css
  src/pages/galleryPages/ui/GalleryPage.tsx
  src/shared/hook/useFileDownload.ts
  src/shared/hook/useFlattenData.ts
  src/shared/ui/galleryCard/GalleryCard.tsx
  src/shared/ui/galleryForm/GalleryForm.tsx
  yarn.lock
Labels: 수정

#129 [Feature] 관리자페이지에서 페이지별 데이터 전체를 받을 수 있도록 size 설정
  src/pages/admin/api/useAdminCompetitionDatas.ts
  src/pages/admin/api/useAdminGalleryDatas.ts
  src/pages/admin/api/useAdminPostDatas.ts
  src/pages/admin/api/useAdminUserDatas.ts
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.tsx
  src/shared/hook/useFileDownload.ts
  src/shared/hook/useFlattenData.ts
Labels: 개발

#136 [QA] 게시글 페이지 피드백
  package-lock.json
  package.json
  src/entities/postListTable/ui/PostListRow.module.css
  src/entities/postListTable/ui/PostListTable.tsx
  src/pages/postPage/ui/AddPostPage.module.css
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.tsx
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/lib/ConfirmDelete.ts
  src/widgets/searchBar/ui/SearchBar.tsx
  yarn.lock
Labels: 버그, 수정

#137 [QA] 페이지 이동시 검색바 상태 초기화
  src/pages/postPage/ui/PostListPage.tsx
  src/widgets/searchBar/ui/SearchBar.tsx
Labels: 버그, 수정

#139 [FIX] 관리자 게시물 페이지 등록 버튼 추가 및 다른 수정
  src/features/admin/ui/AdminCompetitionListData.tsx
  src/features/admin/ui/AdminPostListData.tsx
  src/features/admin/ui/AdminUserListData.tsx
  src/pages/admin/api/useAdminCompetitionDatas.ts
  src/pages/admin/api/useAdminGalleryDatas.ts
  src/pages/admin/api/useAdminPostDatas.ts
  src/pages/admin/api/useAdminUserDatas.ts
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.tsx
  src/pages/galleryPages/api/useGalleryEdit.ts
  src/pages/galleryPages/api/useGalleryUpload.ts
Labels: 수정

#141 에러 및 내정보 페이지, 비밀번호 변경 로직 추가
  src/app/App.tsx
  src/entities/user/index.ts
  src/entities/user/ui/ProfileRow.module.css
  src/entities/user/ui/ProfileRow.tsx
  src/features/header/index.ts
  src/features/header/ui/GoToAdmin.tsx
  src/features/header/ui/HeaderGoToBtn.module.css
  src/features/header/ui/HeaderGoToBtn.tsx
  src/features/user/api/FetchUpdatePW.ts
  src/features/user/index.ts
  src/features/user/ui/UpdatePasswordModal.module.css
  src/features/user/ui/UpdatePasswordModal.tsx
  src/pages/competitionPage/ui/PostCompetitionSchedulePage.tsx
  src/pages/loginPage/api/FetchLogin.ts
  src/pages/user/api/FetchGetUserInfo.ts
  src/pages/user/index.ts
  src/pages/user/ui/ProfilePage.module.css
  src/pages/user/ui/ProfilePage.tsx
  src/shared/type/MainType.ts
  src/shared/type/UserType.ts
  src/shared/ui/commonModal/CommonModal.tsx
  src/widgets/competition/ui/CompetitionRow.tsx
  src/widgets/competition/ui/PostResultBox.tsx
  src/widgets/competition/ui/PostScheduleBox.tsx
  src/widgets/header/ui/Header.tsx
  src/widgets/main/ui/AnnouncementCard.tsx
  src/widgets/main/ui/AnnouncementCarousel.tsx
  src/widgets/user/api/FetchUpdateProfile.ts
  src/widgets/user/index.ts
  src/widgets/user/ui/ProfileForm.module.css
  src/widgets/user/ui/ProfileForm.tsx
  src/widgets/user/ui/UpdateProfileForm.module.css
  src/widgets/user/ui/UpdateProfileForm.tsx
Labels: 개발

#145 [fix] post page foreword 데이터 삭제
  public/icon/delete.svg
  src/entities/postListTable/ui/PostListRow.tsx
  src/pages/postPage/api/AddPostRequest.ts
  src/pages/postPage/api/EditPostRequest.ts
  src/pages/postPage/ui/AddPostPage.module.css
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/UpdatePostPage.module.css
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/type/AdminType.ts
  src/shared/type/PostType.ts
Labels: 수정
