Repository JBA-jeju-basketball-association/JBA-FE, pull requests merged in 2024-06, with the labels that each got.

#59 [Feature] 검색기능 구현, 갤러디상세 슬라이드 설정
  src/entity/galleryImageInput/ui/galleryImageInput.module.css
  src/entity/galleryImageInput/ui/index.tsx
  src/features/galleryDetailModal/ui/galleryDetail.module.css
  src/pages/galleryPage/ui/galleryPage.module.css
  src/pages/galleryPage/ui/index.tsx
  src/shared/ui/commonModal/index.tsx
Labels: 개발

#61 배포
  ,
  package-lock.json
  src/entities/MenuBar/lib/menrLink.ts
  src/entities/MenuBar/ui/MenuBar.module.css
  src/entities/MenuBar/ui/MenuBar.tsx
  src/entity/galleryImageInput/ui/galleryImageInput.module.css
  src/entity/galleryImageInput/ui/index.tsx
  src/features/galleryDetailModal/ui/galleryDetail.module.css
  src/pages/galleryPage/ui/galleryPage.module.css
  src/pages/galleryPage/ui/index.tsx
  src/shared/base.css
  src/shared/colors.css
  src/shared/ui/Logo/Logo.tsx
  src/shared/ui/Logo/logo.module.css
  src/shared/ui/commonModal/index.tsx
  yarn.lock
Labels: 개발

#65 Fix competition
  public/index.html
  src/app/header/Header.module.css
  src/app/header/Header.tsx
  src/entities/competition/index.ts
  src/entities/competition/ui/CompetitionDetailInfoRow.module.css
  src/entities/competition/ui/CompetitionDetailInfoRow.tsx
  src/features/competition/ui/PlaceArea.module.css
  src/features/datepicker/ui/CustomDatePicker.module.css
  src/features/datepicker/ui/CustomDatePickerWithTime.module.css
  src/features/header/ui/LoginButton.module.css
  src/features/header/ui/SignUpButton.module.css
  src/features/header/ui/SignUpButton.tsx
  src/pages/competitionPage/ui/AddCompetitionPage.module.css
  src/pages/competitionPage/ui/AddResultPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionResultPage.module.css
  src/pages/loginPage/ui/LoginPage.module.css
  src/shared/colors.css
  src/shared/ui/addCompetitionLabel/AddCompetitionLabel.module.css
  src/shared/ui/competitionLabel/CompetitionDetailLabel.module.css
  src/shared/ui/loginInput/LoginInput.module.css
  src/shared/ui/regitUpdateDeleteButton/RegitUpdateDeleteButton.module.css
  src/widgets/competition/ui/AddResultRow.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.tsx
  src/widgets/competition/ui/CompetitionResult.module.css
  src/widgets/competition/ui/CompetitionTitleArea.module.css
  src/widgets/competition/ui/KakaoMap.module.css
  src/widgets/competition/ui/ResultList.module.css
  src/widgets/competition/ui/ResultRow.module.css
  src/widgets/searchBar/ui/SearchBar.module.css
Labels: 개발

#67 #66 feat: main page 에 competition 부분 구현 및 react-slick 을 이용하여 carousel…
  package.json
  src/app/App.module.css
  src/app/App.tsx
  src/pages/mainPage/ui/Main.module.css
  src/pages/mainPage/ui/Main.tsx
  src/shared/api/Api.ts
  src/shared/api/NormalApi.ts
  src/shared/base.css
  src/shared/lib/formatDate2.ts
  src/shared/type/MainType.ts
  src/shared/ui/index.ts
  src/shared/ui/mainTitle/MainTitle.module.css
  src/shared/ui/mainTitle/MainTitle.tsx
  src/shared/ui/navigateAllItemBtn/navigateAllItemBtn.module.css
  src/shared/ui/navigateAllItemBtn/navigateAllItemBtn.tsx
  src/widgets/competition/ui/CompetitionRow.module.css
  src/widgets/competition/ui/FloorBox.module.css
  src/widgets/competition/ui/FloorBox.tsx
  src/widgets/competition/ui/ResultRow.module.css
  src/widgets/competition/ui/UpdateFloorBox.module.css
  src/widgets/main/api/FetchMainCompetitionList.ts
  src/widgets/main/index.ts
  src/widgets/main/ui/CompetitionArea.module.css
  src/widgets/main/ui/CompetitionArea.tsx
  src/widgets/main/ui/CompetitionCard.module.css
  src/widgets/main/ui/CompetitionCard.tsx
  src/widgets/main/ui/CompetitionCarousel.tsx
  yarn.lock
Labels: 개발

#68 [Feat] post list page
  ckeditor5/node_modules/typescript/bin/tsc
  ckeditor5/node_modules/typescript/bin/tsserver
  package-lock.json
  src/app/App.tsx
  src/entities/postListTable/index.tsx
  src/entities/postListTable/ui/PostListRow.module.css
  src/entities/postListTable/ui/PostListRow.tsx
  src/entities/postListTable/ui/PostListTable.module.css
  src/entities/postListTable/ui/PostListTable.tsx
  src/pages/competitionPage/api/FetchGetCompetitionList.ts
  src/pages/competitionPage/ui/CompetitionPage.tsx
  src/pages/postPage/api/DeletePost.ts
  src/pages/postPage/api/FetchPostDetail.ts
  src/pages/postPage/api/FetchPostList.ts
  src/pages/postPage/api/PatchPostDetail.ts
  src/pages/postPage/index.ts
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.module.css
  src/pages/postPage/ui/PostListPage.tsx
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/api/NormalApi.ts
  src/shared/type/PostType.ts
  src/widgets/main/ui/CompetitionCarousel.tsx
  yarn.lock
Labels: 개발

#73 [Feat] Post Detail Page 첨부파일 다운로드 기능 구현
  src/pages/postPage/ui/PostDetailPage.module.css
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.module.css
  src/shared/ui/Button.tsx
  src/shared/ui/button/Button.module.css
  src/shared/ui/button/index.tsx
Labels: 개발

#76 Fix login page
  ,
  .gitignore
  .idea/workspace.xml
  public/loginPage/loginPagebackgroundImg.jpg
  src/entities/MenuBar/ui/MenuBar.module.css
  src/pages/competitionPage/ui/PrivateRoute.tsx
  src/pages/loginPage/api/FetchLogin.ts
  src/pages/loginPage/ui/LoginPage.module.css
  src/pages/loginPage/ui/LoginPage.tsx
  src/shared/api/UseAxiosInterceptor.ts
  src/shared/model/index.ts
  src/shared/model/stores/GalleryModalStore.ts
  src/shared/model/svgComponent/Check.tsx
  src/shared/model/svgComponent/WhiteLogo.tsx
  src/shared/ui/checkBox/CheckBox.module.css
  src/shared/ui/checkBox/CheckBox.tsx
  src/shared/ui/galleryCard/index.tsx
  src/shared/ui/index.ts
  src/shared/ui/loginInput/LoginInput.module.css
  src/shared/ui/loginInput/LoginInput.tsx
  src/utils/cookie/cookie.ts
  src/widgets/competition/ui/CompetitionDetailInfo.tsx
  src/widgets/header/ui/Header.tsx
  src/widgets/main/ui/GalleryArea.module.css
  src/widgets/main/ui/GalleryArea.tsx
Labels: 개발

#77 배포
  ,
  .gitignore
  .idea/workspace.xml
  package-lock.json
  package.json
  public/loginPage/loginPagebackgroundImg.jpg
  src/app/App.tsx
  src/entities/MenuBar/ui/MenuBar.module.css
  src/entities/MenuBar/ui/MenuBar.tsx
  src/entities/postListTable/ui/PostListTable.tsx
  src/pages/competitionPage/ui/PrivateRoute.tsx
  src/pages/loginPage/api/FetchLogin.ts
  src/pages/loginPage/ui/LoginPage.module.css
  src/pages/loginPage/ui/LoginPage.tsx
  src/pages/postPage/api/FetchPostDetail.ts
  src/pages/postPage/ui/PostDetailPage.module.css
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.module.css
  src/pages/postPage/ui/PostListPage.tsx
  src/shared/api/UseAxiosInterceptor.ts
  src/shared/model/index.ts
  src/shared/model/stores/GalleryModalStore.ts
  src/shared/model/svgComponent/Check.tsx
  src/shared/model/svgComponent/WhiteLogo.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/button/Button.module.css
  src/shared/ui/button/index.tsx
  src/shared/ui/checkBox/CheckBox.module.css
  src/shared/ui/checkBox/CheckBox.tsx
  src/shared/ui/galleryCard/index.tsx
  src/shared/ui/index.ts
  src/shared/ui/loginInput/LoginInput.module.css
  src/shared/ui/loginInput/LoginInput.tsx
  src/utils/cookie/cookie.ts
  src/widgets/competition/ui/CompetitionDetailInfo.tsx
  src/widgets/header/ui/Header.tsx
  src/widgets/main/ui/GalleryArea.module.css
  src/widgets/main/ui/GalleryArea.tsx
  yarn.lock
Labels: 개발

#83 Fix competition
  .idea/workspace.xml
  src/app/App.css
  src/app/PrivateRoute.tsx
  src/entities/MenuBar/ui/MenuBar.module.css
  src/entities/MenuBar/ui/MenuBar.tsx
  src/entities/competition/ui/CompetitionDetailInfoRow.module.css
  src/entities/competition/ui/CompetitionDetailInfoRow.tsx
  src/features/competition/ui/AddFiles.module.css
  src/features/competition/ui/AddFiles.tsx
  src/features/competition/ui/CompetitionDetailCategory.module.css
  src/features/competition/ui/CompetitionStatusFilter.module.css
  src/features/competition/ui/CompetitionStatusFilter.tsx
  src/features/competition/ui/FileRow.tsx
  src/features/competition/ui/PlaceArea.module.css
  src/features/competition/ui/PlaceArea.tsx
  src/features/competition/ui/UpdateFiles.tsx
  src/features/competition/ui/UploadedFileRow.tsx
  src/pages/competitionPage/index.ts
  src/pages/competitionPage/ui/AddCompetitionPage.module.css
  src/pages/competitionPage/ui/AddCompetitionPage.tsx
  src/pages/competitionPage/ui/AddResultPage.module.css
  src/pages/competitionPage/ui/CompetitionDetailPage.module.css
  src/pages/competitionPage/ui/CompetitionDetailPage.tsx
  src/pages/competitionPage/ui/CompetitionPage.module.css
  src/pages/competitionPage/ui/CompetitionPage.tsx
  src/pages/competitionPage/ui/UpdateCompetitionPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionPage.tsx
  src/pages/competitionPage/ui/UpdateCompetitionResultPage.module.css
  src/shared/model/Year.ts
  src/shared/model/index.ts
  src/shared/ui/addCompetitionLabel/AddCompetitionLabel.module.css
  src/shared/ui/addCompetitionLabel/AddCompetitionLabel.tsx
  src/shared/ui/competitionLabel/CompetitionDetailLabel.module.css
  src/shared/ui/index.ts
  src/shared/ui/listLinkBtn/ListLinkBtn.module.css
  src/shared/ui/listLinkBtn/ListLinkBtn.tsx
  src/shared/ui/pageTitle/PageTitle.module.css
  src/shared/ui/pageTitle/PageTitle.tsx
  src/shared/ui/regitTitleInput/RegitTitleInput.module.css
  src/shared/ui/regitTitleInput/RegitTitleInput.tsx
  src/shared/ui/regitUpdateDeleteButton/RegitUpdateDeleteButton.module.css
  src/widgets/competition/ui/AddResultRow.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.tsx
  src/widgets/competition/ui/CompetitionDetailTitle.module.css
  src/widgets/competition/ui/CompetitionDetailTitle.tsx
  src/widgets/competition/ui/CompetitionRow.module.css
  src/widgets/competition/ui/CompetitionRow.tsx
  src/widgets/competition/ui/CompetitionTitleArea.module.css
  src/widgets/competition/ui/CompetitionTitleArea.tsx
  src/widgets/competition/ui/FloorBox.tsx
  src/widgets/competition/ui/ResultList.module.css
  src/widgets/competition/ui/ResultRow.module.css
  src/widgets/header/index.ts
  src/widgets/header/ui/Header.module.css
  src/widgets/header/ui/Header.tsx
  src/widgets/pagination/ui/Pagination.module.css
  src/widgets/pagination/ui/Pagination.tsx
Labels: 개발

#84 #78 fix: galleryPage min-width: 1920px 로 변경
  .idea/workspace.xml
  src/pages/galleryPages/ui/GalleryEditPage.module.css
  src/pages/galleryPages/ui/GalleryUploadPage.module.css
Labels: 개발

#85 배포
  .idea/workspace.xml
  src/app/App.css
  src/app/PrivateRoute.tsx
  src/entities/MenuBar/ui/MenuBar.module.css
  src/entities/MenuBar/ui/MenuBar.tsx
  src/entities/competition/ui/CompetitionDetailInfoRow.module.css
  src/entities/competition/ui/CompetitionDetailInfoRow.tsx
  src/features/competition/ui/AddFiles.module.css
  src/features/competition/ui/AddFiles.tsx
  src/features/competition/ui/CompetitionDetailCategory.module.css
  src/features/competition/ui/CompetitionStatusFilter.module.css
  src/features/competition/ui/CompetitionStatusFilter.tsx
  src/features/competition/ui/FileRow.tsx
  src/features/competition/ui/PlaceArea.module.css
  src/features/competition/ui/PlaceArea.tsx
  src/features/competition/ui/UpdateFiles.tsx
  src/features/competition/ui/UploadedFileRow.tsx
  src/pages/competitionPage/index.ts
  src/pages/competitionPage/ui/AddCompetitionPage.module.css
  src/pages/competitionPage/ui/AddCompetitionPage.tsx
  src/pages/competitionPage/ui/AddResultPage.module.css
  src/pages/competitionPage/ui/CompetitionDetailPage.module.css
  src/pages/competitionPage/ui/CompetitionDetailPage.tsx
  src/pages/competitionPage/ui/CompetitionPage.module.css
  src/pages/competitionPage/ui/CompetitionPage.tsx
  src/pages/competitionPage/ui/UpdateCompetitionPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionPage.tsx
  src/pages/competitionPage/ui/UpdateCompetitionResultPage.module.css
  src/pages/galleryPages/ui/GalleryEditPage.module.css
  src/pages/galleryPages/ui/GalleryUploadPage.module.css
  src/shared/model/Year.ts
  src/shared/model/index.ts
  src/shared/ui/addCompetitionLabel/AddCompetitionLabel.module.css
  src/shared/ui/addCompetitionLabel/AddCompetitionLabel.tsx
  src/shared/ui/competitionLabel/CompetitionDetailLabel.module.css
  src/shared/ui/index.ts
  src/shared/ui/listLinkBtn/ListLinkBtn.module.css
  src/shared/ui/listLinkBtn/ListLinkBtn.tsx
  src/shared/ui/pageTitle/PageTitle.module.css
  src/shared/ui/pageTitle/PageTitle.tsx
  src/shared/ui/regitTitleInput/RegitTitleInput.module.css
  src/shared/ui/regitTitleInput/RegitTitleInput.tsx
  src/shared/ui/regitUpdateDeleteButton/RegitUpdateDeleteButton.module.css
  src/widgets/competition/ui/AddResultRow.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.module.css
  src/widgets/competition/ui/CompetitionDetailInfo.tsx
  src/widgets/competition/ui/CompetitionDetailTitle.module.css
  src/widgets/competition/ui/CompetitionDetailTitle.tsx
  src/widgets/competition/ui/CompetitionRow.module.css
  src/widgets/competition/ui/CompetitionRow.tsx
  src/widgets/competition/ui/CompetitionTitleArea.module.css
  src/widgets/competition/ui/CompetitionTitleArea.tsx
  src/widgets/competition/ui/FloorBox.tsx
  src/widgets/competition/ui/ResultList.module.css
  src/widgets/competition/ui/ResultRow.module.css
  src/widgets/header/index.ts
  src/widgets/header/ui/Header.module.css
  src/widgets/header/ui/Header.tsx
  src/widgets/pagination/ui/Pagination.module.css
  src/widgets/pagination/ui/Pagination.tsx
Labels: 개발

#88 #78 fix: 전체 페이지 min-width:1440px 로 변경
  .idea/workspace.xml
  src/app/App.css
  src/app/header/Header.module.css
  src/entities/MenuBar/ui/MenuBar.module.css
  src/pages/competitionPage/ui/AddCompetitionPage.module.css
  src/pages/competitionPage/ui/AddResultPage.module.css
  src/pages/competitionPage/ui/CompetitionDetailPage.module.css
  src/pages/competitionPage/ui/CompetitionPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionPage.module.css
  src/pages/competitionPage/ui/UpdateCompetitionResultPage.module.css
  src/pages/galleryPages/ui/GalleryEditPage.module.css
  src/pages/galleryPages/ui/GalleryPage.module.css
  src/pages/galleryPages/ui/GalleryUploadPage.module.css
  src/pages/loginPage/ui/LoginPage.module.css
  src/pages/mainPage/ui/Main.module.css
  src/pages/postPage/ui/AddPostPage.module.css
  src/pages/postPage/ui/PostDetailPage.module.css
  src/pages/postPage/ui/PostListPage.module.css
  src/pages/postPage/ui/UpdatePostPage.module.css
  src/widgets/footer/ui/Footer.module.css
  src/widgets/main/ui/Banner.module.css
Labels: 개발

#94 [Fix] post list page refatch 요청을 위한 쿼리키 추가
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/PostListPage.tsx
Labels: 수정

#96 adminPage Layout 구현
  .gitignore
  .idea/workspace.xml
  package.json
  src/app/App.tsx
  src/app/PrivateRoute.tsx
  src/features/header/index.ts
  src/features/header/ui/GoToAdmin.module.css
  src/features/header/ui/GoToAdmin.tsx
  src/pages/admin/index.ts
  src/pages/admin/ui/Admin.module.css
  src/pages/admin/ui/Admin.tsx
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.tsx
  src/shared/lib/JwtDecoder.ts
  src/widgets/header/index.ts
  src/widgets/header/ui/Header.module.css
  src/widgets/header/ui/Header.tsx
  yarn.lock
Labels: 개발

#98 master pr 미스로 develop에도 반영
  .gitignore
  .idea/workspace.xml
  package.json
  src/app/App.tsx
  src/app/PrivateRoute.tsx
  src/features/header/index.ts
  src/features/header/ui/GoToAdmin.module.css
  src/features/header/ui/GoToAdmin.tsx
  src/pages/admin/index.ts
  src/pages/admin/ui/Admin.module.css
  src/pages/admin/ui/Admin.tsx
  src/pages/admin/ui/AdminCompetition.tsx
  src/pages/admin/ui/AdminGallery.tsx
  src/pages/admin/ui/AdminPost.tsx
  src/pages/admin/ui/AdminUser.tsx
  src/shared/lib/JwtDecoder.ts
  src/widgets/header/index.ts
  src/widgets/header/ui/Header.module.css
  src/widgets/header/ui/Header.tsx
  yarn.lock
Labels: 수정

#97 [Feat] 게시글 작성,수정 시 글 종류 옵션 추가
  src/pages/postPage/api/AddPostRequest.ts
  src/pages/postPage/api/EditPostRequest.ts
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/model/officialOptions.ts
Labels: 개발

#99 [Feat] 게시글 작성 첨부파일 업로드 기능 구현 / 게시글 글종류, 머리말 상태관리 로직 수정 / 게시글 상세 페이지 첨부파일 다운로드 기능 구현
  package-lock.json
  src/pages/postPage/api/AddPostRequest.ts
  src/pages/postPage/api/EditPostRequest.ts
  src/pages/postPage/api/GetFilesUrlRequest.ts
  src/pages/postPage/ui/AddPostPage.tsx
  src/pages/postPage/ui/PostDetailPage.tsx
  src/pages/postPage/ui/UpdatePostPage.tsx
  src/shared/model/forewordOptions.ts
  src/shared/model/officialOptions.ts
  src/shared/type/PostType.ts
  yarn.lock
Labels: 수정, 개발
